# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 326b03de9bbd077a419bcff9f70465851c65d5c6b829e8865cb015b1aa6770576aba94fb0c4d1e07fd567fafd160853cc7d9799481ac86e0e985a655385301c4

test:
  secret_key_base: 5e77d02ebd708a2d5b6b34bb32821a83a84ea6323e983baf2ea78f778f61711b107cc2586f51976a0a3b88953cab47d2a5617140d08cbd4517586047bed0dda8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
